# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
# replicaCount: 1

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
# image:
# repository: nginx
# Overrides the image tag whose default is the chart appVersion.
tag:

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
# service:
# This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
# type: ClusterIP
# This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
# port: 80

db:
  url:
  username:
  password:
