apiVersion: apps/v1
kind: Deployment
metadata:
  name: productservice-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: sunnylucas/productservice:{{.Values.tag}}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          # env:
          #   - name: DB_URL
          #     value: "{{ .Values.db.url }}"
          #   - name: DB_USERNAME
          #     value: "{{ .Values.db.username }}"
          #   - name: DB_PASSWORD
          #     value: "{{ .Values.db.password }}"
          volumeMounts:
            - name: config-volume
              mountPath: /appdir/config
      volumes:
        - name: config-volume
          secret:
            secretName: productservice-secret
