apiVersion: apps/v1
kind: Deployment
metadata:
  name: productservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: sunnylucas/productservice:{{.Values.tag}}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: config-volume
              mountPath: /appdir/config
      volumes:
        - name: config-volume
          secret:
            secretName: productservice-secret
