apiVersion: v1
kind: Secret
metadata:
  name: productservice-secret
type: Opaque
stringData:
  application.properties: |
    spring.datasource.url={{.Values.db.url}}
    spring.datasource.username={{.Values.db.username}}
    spring.datasource.password={{.Values.db.password}}
