name: Continuous Integration on Merge Request

on:
  pull_request:
    branches:
      - "release*"

jobs:
  test_build:
    name: Test and Build application Build container image
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Maven verify
        run: mvn -B verify

      - name: Build container image
        run: |
          cd target
          ls

    # - name: Set up JDK 17
    #   uses: actions/setup-java@v4
    #   with:
    #     java-version: "17"
    #     distribution: "temurin"
    #     cache: maven

    # - name: Test Application
    #   run: mvn -B test

    # - name: Build Application
    #   run: mvn -B package -DskipTests
