name: CI Pull Request

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "release*"

jobs:
  test_build:
    name: Test, Build Container Image, & Push
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn clean package org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.organization=shopzone \
          -Dsonar.projectKey=sunnypereira_shopzone

      - name: Create Tag
        id: create_tag
        # run: echo "NOW=$(date +'%Y-%m-%dT%H-%M-%S')" >> $GITHUB_ENV
        run: |
          NOW=$(date +'%Y%m%dT%H%M%S')
          SHORT_SHA=${GITHUB_SHA::7}
          IMAGE_TAG="${NOW}-${SHORT_SHA}"          
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "Using image tag: $IMAGE_TAG"

      - name: Build Container image
        run: docker build -t ${{vars.CONTAINER_REGISTRY_ADDRESS}}/${{ vars.CONTAINER_REGISTRY_USERNAME }}/productservice:$IMAGE_TAG .

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ vars.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_HUB_PAT }}

      - name: Push Container image to Container Registry
        run: |
          docker push ${{vars.CONTAINER_REGISTRY_ADDRESS}}/${{ vars.CONTAINER_REGISTRY_USERNAME }}/productservice:$IMAGE_TAG
