name: CI Pull Request

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "release*"

jobs:
  test_build:
    name: Test and Build application Build container image
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      # - name: Build and analyze
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #   run: |
      #     mvn clean package org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
      #     -Dsonar.organization=shopzone \
      #     -Dsonar.projectKey=sunnypereira_shopzone

      - name: Build
        run: |
          mvn clean package -DskipTests

      - name: Set current date as env variable
        id: date_time
        run: echo "NOW=$(date +'%Y-%m-%dT%H-%M-%S')" >> $GITHUB_ENV

      - name: Build Container image
        run: docker build -t shopzone/productservice:${GITHUB_SHA::7}-$NOW .

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # - name: Azure CLI script
      #   uses: azure/cli@v2
      #   with:
      #     azcliversion: latest
      #     inlineScript: |
      #       az account show

      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_REGISTRY_NAME }}.azurecr.io
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Push Docker image to Azure Container Registry
        run: |
          docker tag shopzone/productservice:${GITHUB_SHA::7}-$NOW ${{ secrets.ACR_REGISTRY_NAME }}.azurecr.io/shopzone/productservice:${GITHUB_SHA::7}-$NOW
          docker push ${{ secrets.ACR_REGISTRY_NAME }}.azurecr.io/shopzone/productservice:${GITHUB_SHA::7}-$NOW
