name: CI Pull Request

on:
  push:
  pull_request:
    branches:
      - "release*"

jobs:
  test_build:
    name: Test and Build application Build container image
    runs-on: ubuntu-latest

    steps:
      - name: Set current date as env variable
        id: date_time
        run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
      - name: Echo current date
        run: echo $NOW

      - name: Set some environment variables
        run: |
          echo "MY_VAR1=Hello" >> $GITHUB_ENV
          echo "MY_VAR2=World" >> $GITHUB_ENV
      - name: Print all environment variables
        run: |
          echo "All environment variables:"
          env

      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner. Sha is ${{github.sha}} $NOW"

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Maven verify
        run: mvn -B verify

      - name: Build container image
        run: |
