name: CI Push

on:
  push:
    branches-ignore:
      - "main"
      - "release*"
  workflow_dispatch:

jobs:
  test-build:
    name: Test, Build and Analyse application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner. "

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      # - name: Build and analyze
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #   run: |
      #     mvn clean package org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
      #     -Dsonar.organization=shopzone \
      #     -Dsonar.projectKey=sunnypereira_shopzone

      - name: Set current date as env variable
        id: date_time
        run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV

      - name: Build Container image
        run: |
          mvn clean package
          echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
          docker build -t shopzone/productservice:${GITHUB_SHA::7}-${env.NOW} .
          docker images -a
