name: CI Pull Request

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "release*"

jobs:
  test_build:
    name: Test, Build Container Image, & Push
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn clean package org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.organization=shopzone \
          -Dsonar.projectKey=sunnypereira_shopzone

      - name: Set current date as env variable
        id: date_time
        run: echo "NOW=$(date +'%Y-%m-%dT%H-%M-%S')" >> $GITHUB_ENV

      - name: Build Container image
        run: docker build -t ${{ vars.CONTAINER_REGISTRY_USERNAME }}/productservice:${GITHUB_SHA::7}-$NOW .

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ vars.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_HUB_PAT }}

      - name: Push Container image to Container Registry
        run: |
          docker push ${{ vars.CONTAINER_REGISTRY_USERNAME }}/productservice:${GITHUB_SHA::7}-$NOW
